import { z } from 'zod';

export const CaseFileSchema = z.object({
  variantlens_version: z.string(),
  variant: z.string(),
  timestamp: z.string().datetime(),
  structure: z.object({
    source: z.enum(['PDB', 'AlphaFold', 'Partial']),
    id: z.string(),
    resolution: z.number().optional(),
    plddt: z.array(z.number()).optional(),
    coverage: z.string(),
    url: z.string().url(),
  }),
  context: z.object({
    gene_function: z.string(),
    domain_context: z.string(),
    known_annotations: z.array(z.string()),
    clinvar_summary: z.string().nullable(),
    confidence: z.enum(['high', 'moderate', 'low']),
  }),
  hypothesis: z.object({
    text: z.string(),
    confidence: z.enum(['high', 'moderate', 'low', 'uncertain']),
    citations: z.array(z.object({
      pmid: z.string(),
      title: z.string(),
    })),
    structural_basis: z.array(z.string()),
  }),
  validation: z.object({
    flags: z.array(z.string()),
    final_confidence: z.string(),
  }),
  metadata: z.object({
    analysis_time_ms: z.number(),
    cache_hits: z.number(),
  }).optional(),
});

export type CaseFile = z.infer<typeof CaseFileSchema>;

export function generateCaseFile(data: any): CaseFile {
  const caseFile: CaseFile = {
    variantlens_version: '2.0.0',
    variant: data.variant,
    timestamp: data.timestamp || new Date().toISOString(),
    structure: data.structure,
    context: data.context,
    hypothesis: data.hypothesis,
    validation: data.validation,
  };

  // Validate
  return CaseFileSchema.parse(caseFile);
}

export function generateMarkdown(caseFile: CaseFile): string {
  return `# VariantLens Analysis Report

## Variant Information
- **Variant:** ${caseFile.variant}
- **Generated:** ${caseFile.timestamp}
- **Version:** ${caseFile.variantlens_version}

## Structural Context
- **Source:** ${caseFile.structure.source}
- **ID:** ${caseFile.structure.id}
${caseFile.structure.resolution ? `- **Resolution:** ${caseFile.structure.resolution}Å` : ''}
- **Coverage:** ${caseFile.structure.coverage}

## Biological Context
${caseFile.context.gene_function}

**Domain Context:** ${caseFile.context.domain_context}

## Mechanism Hypothesis
${caseFile.hypothesis.text}

**Confidence:** ${caseFile.hypothesis.confidence}

### Structural Basis
${caseFile.hypothesis.structural_basis.map(b => `- ${b}`).join('\n')}

## Citations
${caseFile.hypothesis.citations.map(c => `- [${c.pmid}](https://pubmed.ncbi.nlm.nih.gov/${c.pmid}/): ${c.title}`).join('\n')}

${caseFile.hypothesis.citations.length === 0 ? '*No direct literature found*' : ''}

## Validation Notes
${caseFile.validation.flags.length > 0 
  ? `Flags: ${caseFile.validation.flags.join(', ')}` 
  : 'No validation flags'}

---
*Generated by VariantLens-Open v${caseFile.variantlens_version} for research and educational purposes only. Not for clinical use.*
`;
}
