"use client";

import { motion } from "framer-motion";
import { FileText, AlertTriangle, Hexagon, AlertCircle, Info, Beaker, HelpCircle, ExternalLink } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { clsx } from "clsx";
import StructureViewer from "./StructureViewer";

// ==========================================
// TYPES FOR HONEST RESPONSE
// ==========================================

interface EvidenceCoverage {
  structure: {
    status: string; // 'experimental' | 'predicted' | 'none'
    source?: string;
    id?: string;
    resolution?: number;
    note?: string;
    sifts?: {
      mapped: boolean;
      pdbId: string;
      chain: string;
      pdbResidue: string;
      source: string;
    };
  };
  clinical: {
    status: string;
    source?: string;
    significance?: string;     // Phase-2: ClinVar
    reviewStatus?: string;
    stars?: number;
    clinvarId?: string;
    url?: string;
    conditions?: string[];
  };
  domain: {
    inAnnotatedDomain: boolean;
    domainName?: string;
  };
  literature: {
    variantSpecificCount: number;
    query?: string;
    papers?: Array<{
      title: string;
      url: string;
      source: string;
      year: string;
    }>;
    note?: string;
  };
}

interface ExplicitUnknowns {
  items: string[];
  severity: 'critical' | 'moderate' | 'minor';
}

interface HonestReportData {
  variant: {
    hgvs: string;
    gene: string;
    residue: number;
  };
  coverage: EvidenceCoverage;
  unknowns: ExplicitUnknowns;
  curatedInfo: any;
}

// Helper to generate Markdown content
function generateMarkdown(data: HonestReportData): string {
  const { variant, coverage, unknowns } = data;
  const date = new Date().toLocaleDateString();
  
  return `# VariantLens Evidence Briefing
**Variant:** ${variant.hgvs} (${variant.gene})
**Date:** ${date}

## 1. Evidence Coverage
| Source | Status | Details |
| :--- | :--- | :--- |
| **Structure** | ${coverage.structure.status} | ${coverage.structure.id || 'N/A'} (${coverage.structure.source || '-'}) |
| **ClinVar** | ${coverage.clinical.status} | ${coverage.clinical.significance || '-'} |
| **Literature** | ${coverage.literature.variantSpecificCount} papers | Query: "${coverage.literature.query || ''}" |
| **SIFTS** | ${coverage.structure.sifts?.mapped ? 'Mapped' : 'Unmapped'} | ${coverage.structure.sifts ? `Chain ${coverage.structure.sifts.chain}:${coverage.structure.sifts.pdbResidue}` : '-'} |

## 2. Evidence Links
- **ClinVar:** ${coverage.clinical.url || 'N/A'}
- **PubMed:** https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(coverage.literature.query || '')}
- **PDB:** ${coverage.structure.id ? `https://www.ebi.ac.uk/pdbe/entry/pdb/${coverage.structure.id}` : 'N/A'}

## 3. Limitations & Unknowns
${unknowns.items.map(item => `- ${item}`).join('\n')}

---
**Evidence Stamp:**
- **Generated:** ${new Date().toISOString()}
- **PDB ID:** ${coverage.structure.id || 'None'}
- **ClinVar ID:** ${coverage.clinical.clinvarId || 'None'}
- **PubMed Query:** "${coverage.literature.query || 'N/A'}"

*Counts are discovery-only and reflect query matches.*
*Generated by VariantLens. This report aggregates evidence and makes no clinical claims.*
`;
}

interface ReportViewProps {
  data: HonestReportData;
}

// ==========================================
// TOOLTIP COMPONENT
// ==========================================

function Tooltip({ children, text }: { children: React.ReactNode; text: string }) {
  return (
    <div className="relative group inline-flex items-center">
      {children}
      <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-2 bg-gray-900 text-xs text-gray-300 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap z-50 border border-white/10 max-w-xs text-wrap">
        {text}
      </div>
    </div>
  );
}

// ==========================================
// EVIDENCE STATUS INDICATOR
// ==========================================

function StatusBadge({ status, label, tooltip }: { status: 'good' | 'warn' | 'none'; label: string; tooltip?: string }) {
  const content = (
    <div className="flex items-center gap-2">
      <div className={clsx(
        "w-2 h-2 rounded-full flex-shrink-0",
        status === 'good' && "bg-green-400",
        status === 'warn' && "bg-yellow-400",
        status === 'none' && "bg-gray-600"
      )} />
      <span className="text-sm text-gray-300">{label}</span>
      {tooltip && <HelpCircle className="w-3 h-3 text-gray-500" />}
    </div>
  );
  
  return tooltip ? <Tooltip text={tooltip}>{content}</Tooltip> : content;
}

// ==========================================
// MAIN COMPONENT
// ==========================================

export default function ReportView({ data }: ReportViewProps) {
  const { variant, coverage, unknowns, curatedInfo } = data;
  
  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="w-full max-w-7xl mx-auto pb-32 px-4 md:px-8"
    >
      {/* RESEARCH USE ONLY - Visible without scrolling */}
      <div className="mb-4 text-center">
        <span className="text-xs font-mono text-yellow-500 bg-yellow-500/10 px-3 py-1 rounded-full border border-yellow-500/30">
          ⚠️ RESEARCH USE ONLY — NOT FOR CLINICAL DECISIONS
        </span>
      </div>

      {/* HEADER ACTIONS (Export) */}
      <div className="flex justify-end gap-2 mb-4 print:hidden">
        <button 
            onClick={() => {
                const md = generateMarkdown(data);
                const blob = new Blob([md], { type: 'text/markdown' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${data.variant.hgvs.replace(/[^a-zA-Z0-9]/g, '_')}_briefing.md`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
            }}
            className="flex items-center gap-2 px-3 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-xs font-mono text-gray-300 transition-colors border border-white/10"
        >
            <FileText className="w-3 h-3" />
            MARKDOWN
        </button>
        <button 
            onClick={() => window.print()}
            className="flex items-center gap-2 px-3 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-xs font-mono text-gray-300 transition-colors border border-white/10"
        >
            <ExternalLink className="w-3 h-3" />
            PDF
        </button>
      </div>

      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-end mb-8 border-b border-white/10 pb-6">
         <div>
             <div className="font-mono text-xs text-primary mb-2 tracking-widest uppercase">Evidence Briefing</div>
             <h2 className="text-4xl md:text-6xl font-heading font-bold text-white tracking-tight uppercase">
                {variant.hgvs}
             </h2>
         </div>
         <div className="flex items-center gap-4 mt-4 md:mt-0 font-mono text-xs text-gray-400">
             <span>{variant.gene}</span>
             <span>|</span>
             <span>{new Date().toLocaleDateString()}</span>
         </div>
      </div>

      {/* ⚠️ UNKNOWNS FIRST (Critical Trust Element) */}
      {unknowns.items.length > 0 && (
        <motion.div 
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className={clsx(
            "mb-8 p-6 rounded-xl border",
            unknowns.severity === 'critical' && "bg-red-500/10 border-red-500/30",
            unknowns.severity === 'moderate' && "bg-yellow-500/10 border-yellow-500/30",
            unknowns.severity === 'minor' && "bg-blue-500/10 border-blue-500/30"
          )}
        >
          <div className="flex items-center gap-2 mb-4">
            <AlertCircle className={clsx(
              "w-5 h-5",
              unknowns.severity === 'critical' && "text-red-400",
              unknowns.severity === 'moderate' && "text-yellow-400",
              unknowns.severity === 'minor' && "text-blue-400"
            )} />
            <h3 className="font-mono text-sm uppercase tracking-widest text-white">
              Evidence Limitations
            </h3>
          </div>
          <ul className="space-y-2">
            {unknowns.items.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-gray-300">
                <span className="text-gray-500">•</span>
                {item}
              </li>
            ))}
          </ul>
        </motion.div>
      )}

      {/* BENTO GRID */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 auto-rows-[minmax(160px,auto)]">
        
        {/* 1. Evidence Coverage Panel */}
        <div className="md:col-span-2 glass-panel p-6 rounded-2xl">
          <h4 className="font-mono text-xs text-muted uppercase tracking-widest mb-4">
            Evidence Coverage
          </h4>
          <div className="grid grid-cols-2 gap-4">
            <StatusBadge 
              status={coverage.structure.status === 'experimental' ? 'good' : coverage.structure.status === 'predicted' ? 'warn' : 'none'}
              label={
                coverage.structure.status === 'none' 
                  ? '❌ No Structure' 
                  : coverage.structure.sifts?.mapped
                    ? `${coverage.structure.source} ${coverage.structure.id} (Chain ${coverage.structure.sifts.chain}:${coverage.structure.sifts.pdbResidue})`
                    : `${coverage.structure.source} ${coverage.structure.id || ''}`
              }
              tooltip={
                coverage.structure.sifts?.mapped 
                  ? `Mapped via SIFTS (Source: ${coverage.structure.sifts.source}). Visualizes residue ${coverage.structure.sifts.pdbResidue} on Chain ${coverage.structure.sifts.chain}.`
                  : coverage.structure.status !== 'none' && coverage.structure.source === 'PDB'
                    ? "Residue mapping not available via SIFTS. Structure may be truncated or disordered in this region."
                    : undefined
              }
            />
            {/* ClinVar Status - Phase-2 */}
            {coverage.clinical.status !== 'none' && coverage.clinical.url ? (
              <a 
                href={coverage.clinical.url} 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-2 hover:bg-white/5 rounded-lg p-1 -m-1 transition-colors"
              >
                <div className="w-2 h-2 rounded-full bg-green-400 flex-shrink-0" />
                <span className="text-sm text-gray-300">
                  {coverage.clinical.significance || coverage.clinical.status}
                  {coverage.clinical.stars !== undefined && (
                    <span className="text-yellow-400 ml-1">{'★'.repeat(coverage.clinical.stars)}{'☆'.repeat(4 - coverage.clinical.stars)}</span>
                  )}
                </span>
                <ExternalLink className="w-3 h-3 text-gray-500" />
              </a>
            ) : (
              <StatusBadge 
                status={'none'}
                label={'❌ No ClinVar Data'}
              />
            )}
            <StatusBadge 
              status={coverage.domain.inAnnotatedDomain ? 'good' : 'none'}
              label={coverage.domain.domainName 
                ? `Domain (UniProt): ${coverage.domain.domainName}` 
                : '❌ Outside Domains'}
              tooltip={coverage.domain.domainName 
                ? "Domain presence alone does not imply functional or clinical impact." 
                : undefined}
            />
            {coverage.literature.variantSpecificCount > 0 ? (
              <a 
                href={`https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(coverage.literature.query || '')}`}
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-2 hover:bg-white/5 rounded-lg p-1 -m-1 transition-colors"
                title={`Search Query: ${coverage.literature.query}\n\nCount reflects PubMed Title/Abstract matches, not curated variant studies.`}
              >
                <div className="w-2 h-2 rounded-full bg-yellow-400 flex-shrink-0" />
                <span className="text-sm text-gray-300">
                  {coverage.literature.variantSpecificCount} papers mention this variant
                </span>
                <ExternalLink className="w-3 h-3 text-gray-500" />
              </a>
            ) : (
              <StatusBadge 
                status={'none'}
                label={'❌ No Papers Found'}
                tooltip={`Search Query: ${coverage.literature.query || 'None'}\n\nCount reflects PubMed Title/Abstract matches.`}
              />
            )}
          </div>
          {coverage.structure.note && (
            <p className="text-xs text-yellow-400/70 mt-4 italic">
              ⚠️ {coverage.structure.note}
            </p>
          )}
        </div>

        {/* 2. Structure Card */}
        <div className="md:col-span-2 md:row-span-2 glass-panel p-1 rounded-2xl relative group overflow-hidden flex flex-col">
          {coverage.structure.status === 'experimental' && coverage.structure.id ? (
             <StructureViewer 
               pdbId={coverage.structure.id}
               sifts={coverage.structure.sifts ? {
                 mapped: coverage.structure.sifts.mapped,
                 chain: coverage.structure.sifts.chain,
                 pdbResidue: coverage.structure.sifts.pdbResidue,
                 source: coverage.structure.sifts.source
               } : undefined}
               uniprotResidue={data.variant.residue}
             />
           ) : (
             <>
               <div className="absolute inset-0 bg-gradient-to-br from-surface to-black z-0" />
               
               <div className="relative z-10 h-full flex flex-col justify-between p-8">
                   {coverage.structure.status !== 'none' ? (
                     <>
                       <div className="flex justify-between items-start">
                          <span className="glass-light px-3 py-1 text-xs font-mono uppercase text-white rounded-full border border-white/10">
                              {coverage.structure.source} ({coverage.structure.status})
                          </span>
                          <Hexagon className="text-primary w-6 h-6 animate-pulse opacity-50"/>
                       </div>
                       
                       <div>
                          <h3 className="text-2xl font-light text-white mb-2">Structure Exists</h3>
                          <p className="text-foreground-muted text-sm max-w-xs">
                            {coverage.structure.status === 'experimental' 
                              ? `Experimental structure exists for this protein region.`
                              : `Predicted structure (AlphaFold) available.`}
                          </p>
                          {coverage.structure.resolution && (
                            <p className="text-xs text-gray-400 mt-1">Resolution: {coverage.structure.resolution}Å</p>
                          )}
                          <p className="text-xs text-yellow-400/60 mt-2 italic">
                            ⚠️ Interactive view not available for this source.
                          </p>
                       </div>
                     </>
                   ) : (
                     <div className="flex flex-col items-center justify-center h-full text-foreground-muted opacity-50">
                        <Hexagon className="w-12 h-12 mb-4 stroke-1"/>
                        <p>No Structure</p>
                     </div>
                   )}
               </div>
             </>
           )}
        </div>

        {/* 3. Curated Context */}
        <div className="md:col-span-2 glass-panel p-6 rounded-2xl">
          <div className="flex items-center gap-2 mb-4">
            <Beaker className="w-4 h-4 text-primary" />
            <h4 className="font-mono text-xs text-muted uppercase tracking-widest">Curated Context (UniProt)</h4>
          </div>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-gray-500">Protein</span>
              <span className="text-white">{curatedInfo.proteinName}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-500">Length</span>
              <span className="text-white">{curatedInfo.proteinLength} aa</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-500">Variant Position</span>
              <span className="text-white">{curatedInfo.variantPosition}</span>
            </div>
            {curatedInfo.variantInDomain && (
              <div className="flex justify-between">
                <span className="text-gray-500">Annotated Domain (UniProt)</span>
                <span className="text-primary">{curatedInfo.variantInDomain}</span>
              </div>
            )}
            <div className="flex justify-between pt-2 border-t border-white/5 mt-2">
              <span className="text-gray-600 text-xs">Isoform</span>
              <span className="text-gray-500 text-xs">Canonical UniProt isoform used</span>
            </div>
          </div>
        </div>

        {/* 4. Domains List (Moved up since Summary Removed) */}
        <div className="md:col-span-2 glass-panel p-6 rounded-2xl">
          <h4 className="font-mono text-xs text-muted uppercase tracking-widest mb-4">
            Annotated Domains (UniProt)
          </h4>
          {curatedInfo.domains && curatedInfo.domains.length > 0 ? (
            <div className="space-y-2">
              {curatedInfo.domains.slice(0, 5).map((domain: any, i: number) => (
                <div key={i} className="text-xs p-2 bg-surface-light/20 rounded">
                  <span className="text-white">{domain.name}</span>
                  <span className="text-gray-500 ml-2">({domain.start}-{domain.end})</span>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-xs text-gray-500 italic">No domains annotated in UniProt</p>
          )}
        </div>

      </div>

      {/* RESEARCH DISCLAIMER (always shown, prominent) */}
      <div className="mt-8 p-6 rounded-xl bg-surface border border-yellow-500/20">
        <div className="flex items-start gap-3">
          <Info className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
          <div className="text-xs text-gray-400 whitespace-pre-line">
            DISCLAIMER: This report is for RESEARCH USE ONLY. It aggregates data from public databases (UniProt, ClinVar, PubMed, PDBe) but has not been manually verified by a clinical geneticist. Do not use for medical decision making.
          </div>
        </div>
      </div>
    </motion.div>
  );
}
