import { NextRequest, NextResponse } from 'next/server';
import { parseHGVS, normalizeVariant } from '@/lib/variant';
import { resolveStructure } from '@/lib/structure';
import { AgentOrchestrator } from '@/lib/agents';
import { variantRateLimiter } from '@/lib/rate-limit';
import { generateCaseFile } from '@/lib/case-file';

export async function POST(request: NextRequest) {
  try {
    // Rate limiting
    const ip = request.ip || 'unknown';
    const allowed = await variantRateLimiter.check(ip);
    
    if (!allowed) {
      const retryAfter = variantRateLimiter.getRetryAfter(ip);
      return NextResponse.json(
        { error: 'Rate limit exceeded', retryAfter },
        { 
          status: 429,
          headers: { 'Retry-After': String(retryAfter) }
        }
      );
    }

    // Parse request
    const body = await request.json();
    const { hgvs, format = 'json' } = body;

    if (!hgvs) {
      return NextResponse.json(
        { error: 'Missing required field: hgvs' },
        { status: 400 }
      );
    }

    // Validate HGVS
    let normalizedVariant;
    try {
      normalizedVariant = normalizeVariant(hgvs);
    } catch (error) {
      return NextResponse.json(
        { error: `Invalid HGVS: ${(error as Error).message}` },
        { status: 400 }
      );
    }

    // Resolve structure
    let structure;
    try {
      // Note: In production, we'd map gene to UniProt first
      const uniprotId = normalizedVariant.parsed.gene; // Simplified
      structure = await resolveStructure(uniprotId, normalizedVariant.parsed.pos);
    } catch (error) {
      if ((error as Error).message.includes('unavailable')) {
        return NextResponse.json(
          { error: 'Structure databases unavailable', fallback: 'text-only-report' },
          { status: 503 }
        );
      }
      return NextResponse.json(
        { error: 'No structure found for this variant' },
        { status: 404 }
      );
    }

    // Run agent analysis
    const orchestrator = new AgentOrchestrator();
    const analysis = await orchestrator.analyze(normalizedVariant.normalized);

    // Build response
    const response = {
      variant: normalizedVariant.normalized,
      structure: {
        source: structure.source,
        id: structure.id,
        url: structure.url,
        resolution: structure.resolution,
        plddt: structure.plddt,
        coverage: structure.coverage,
        experimental: structure.experimental,
      },
      hypothesis: analysis.hypothesis,
      context: analysis.context,
      validation: analysis.validation,
      timestamp: new Date().toISOString(),
      exportUrl: `/api/export/${generateExportId()}`,
    };

    // Return in requested format
    if (format === 'md') {
      const markdown = generateMarkdownReport(response);
      return new NextResponse(markdown, {
        headers: { 'Content-Type': 'text/markdown' },
      });
    }

    return NextResponse.json(response);

  } catch (error) {
    console.error('API error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

function generateExportId(): string {
  return `case-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

function generateMarkdownReport(data: any): string {
  return `# VariantLens Report

**Variant:** ${data.variant}
**Generated:** ${data.timestamp}

## Structure Context
Source: ${data.structure.source} (${data.structure.id})
${data.structure.resolution ? `Resolution: ${data.structure.resolution}Å` : ''}

## Mechanism Hypothesis
${data.hypothesis.text}

**Confidence:** ${data.hypothesis.confidence}

## Structural Basis
${data.hypothesis.structural_basis.map((b: string) => `- ${b}`).join('\n')}

## Citations
${data.hypothesis.citations.map((c: any) => `- [${c.pmid}](https://pubmed.ncbi.nlm.nih.gov/${c.pmid}/)`).join('\n')}

---
*This report was generated by VariantLens-Open for research and educational purposes only. Not for clinical use.*
`;
}
